### ISSUE TITLE
Add support for using either plaintext or HTML output in the translation

### ISSUE THREAD

**Issue by coltongit** [vitalets/google-translate-api#13]
Would it be possible to add in a parameter that allows for either plaintext or HTML output from this API? If done, this will fix https://github.com/matheuss/google-translate-api/issues/81. In that issue, it's suggested that the fix could be an additional `format` parameter that switches between plaintext and HTML output format.

**Comment by coltongit** [comment]
Could this be looked into at some point?

**Comment by vitalets** [comment]
By refs to translate `format` option in https://github.com/matheuss/google-translate-api/issues/81 it looks like HTML is supported by default. 
@coltongit could you provide the code showing when this is needed?

**Comment by vitalets** [comment]
Closing as outdated.

**Comment by JakovGlavac** [comment]
Yeah It would be nice to add format query parametar, because on simple tags like 
```html
<p>hello</p>
```
everything works fine, but when you nest a couple of tags like this (doesn't have to be this extreme):
```html
<p><strong>bold</strong></p><p><em>italic</em></p><p><s>s-prekriženo</s></p><p><code>code</code></p><react-component formula="\frac{{x}^{{2}}}{{69}}" description="" defaultmode="ascii">x^2/69</react-component><img src="https://ucarecdn.com/e7a7f06d-ded8-483f-830b-7817cbcb9c72/-/preview/-/quality/smart/-/format/webp/"><p><sup>na kvadrat</sup></p><p><sub>ispod kvadrata</sub></p><p><a target="_blank" rel="noopener noreferrer nofollow" href="http://localhost:3000/en/question/cl6y814m01718zwvc1zcx3kxj">http://localhost:3000/en/question/cl6y814m01718zwvc1zcx3kxj</a></p><p><math-inline class="math-node">x^2/69</math-inline></p>
``` 
google just ignores it. **Or if** you have something like this:
```html
<p><strong>Bok kaj ima? </strong></p>
``` 
google thinks that because of this strong tag this is english language, when it is croatian.
**or if** you want to translate latin language to Cyrillic (for example Serbian), google translates the tags to Cyrillic as well.
```html
<p><strong>Bok kaj ima? </strong></p>
<п><стронг>Здраво, шта има? </стронг></п>
``` 

So yeah without this parameter it would be _[pain in my assholes](https://youtu.be/E_DtXf0xscI?t=8)_ to extract all the text and then translate it, so I could put it back in place.
