### ISSUE TITLE
Doesn't work in browser

### ISSUE THREAD

**Issue by Fusseldieb** [vitalets/google-translate-api#26]
Hi, 

I've tried to run it in a webapp (Vue) and if I use:
`const translate = require("@vitalets/google-translate-api");`
and launch it, I immediately get an error:
`cannot read property 'tostring' of undefined` from `graceful-fs`
What I've read is that 

> Alright, unfortunately `fs-extra` won't work in web, as it is based on Node. You can send a request from you web app to your Node server, which handles then your folder structure on your server.

*From: https://github.com/jprichardson/node-fs-extra/issues/583#issuecomment-391598788*

Is there any workaround available?

Thanks in advance.

**Comment by vitalets** [comment]
hi @Fusseldieb !
Originally this package is not intended to work in browser for the following reasons:
1. it uses file system to store token
2. it uses cross-domain requests to translate.google.com (until you are google)

The point 1 can be fixed in browser via localstorage , or event memory storage. 
But second can not be fixed in web context. You can only use something allowing cross domain requests:
 - roll own proxy
 - browser extension
 - wrap webpage into app (react-native, electron, etc)

**Comment by Fusseldieb** [comment]
> 2\. it uses cross-domain requests

On a second thought, that makes sense. Browsers don't allow CORS unfortunately, I haven't even thought of that.

Thanks anyways

**Comment by vitalets** [comment]
You are welcome )
